name: Scheduled Audit

# Run weekly code audit and create issues for findings

on:
  schedule:
    # Run every Monday at 9am UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      scope:
        description: 'Audit scope'
        required: false
        default: 'code'
        type: choice
        options:
          - code
          - ux
          - all
      min_severity:
        description: 'Minimum severity'
        required: false
        default: 'high'
        type: choice
        options:
          - low
          - medium
          - high
          - critical

jobs:
  audit:
    runs-on: macos-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9'

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Run SwiftLint
        continue-on-error: true
        run: |
          brew install swiftlint
          swiftlint lint --reporter json > swiftlint-report.json || true

      - name: Analyze Build Warnings
        continue-on-error: true
        run: |
          # Build and capture warnings
          xcodebuild -workspace CameraTest.xcworkspace \
            -scheme CameraTest \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -quiet \
            2>&1 | tee build-output.txt || true

          # Extract warnings
          grep -E "warning:|error:" build-output.txt > build-warnings.txt || true

      - name: Generate Audit Report
        id: audit
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          REPORT_FILE=".claude/audit/reports/$(date +%Y-%m-%d)-ci.json"

          mkdir -p .claude/audit/reports

          # Count issues
          SWIFTLINT_COUNT=$(jq 'length' swiftlint-report.json 2>/dev/null || echo "0")
          BUILD_WARNINGS=$(wc -l < build-warnings.txt | tr -d ' ')

          # Calculate score (simplified)
          TOTAL_ISSUES=$((SWIFTLINT_COUNT + BUILD_WARNINGS))
          if [ $TOTAL_ISSUES -eq 0 ]; then
            SCORE="10.0"
          elif [ $TOTAL_ISSUES -lt 5 ]; then
            SCORE="9.0"
          elif [ $TOTAL_ISSUES -lt 10 ]; then
            SCORE="8.0"
          elif [ $TOTAL_ISSUES -lt 20 ]; then
            SCORE="7.0"
          else
            SCORE="6.0"
          fi

          # Create report
          cat > "$REPORT_FILE" << EOF
          {
            "timestamp": "$TIMESTAMP",
            "scope": "${{ inputs.scope || 'code' }}",
            "source": "ci",
            "score": $SCORE,
            "findings": {
              "swiftlint": $SWIFTLINT_COUNT,
              "buildWarnings": $BUILD_WARNINGS,
              "total": $TOTAL_ISSUES
            }
          }
          EOF

          echo "score=$SCORE" >> $GITHUB_OUTPUT
          echo "total_issues=$TOTAL_ISSUES" >> $GITHUB_OUTPUT
          echo "report_file=$REPORT_FILE" >> $GITHUB_OUTPUT

      - name: Update Project Audit Score
        run: |
          PROJECT_FILE=".claude/project.json"

          if [ -f "$PROJECT_FILE" ]; then
            TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            SCORE="${{ steps.audit.outputs.score }}"

            jq --arg ts "$TIMESTAMP" \
               --argjson score "$SCORE" \
               '
               .audit.lastRun = $ts |
               .audit.lastScope = "code" |
               .audit.score.code = $score |
               .updatedAt = $ts
               ' "$PROJECT_FILE" > tmp.json && mv tmp.json "$PROJECT_FILE"
          fi

      - name: Create Issues for Critical Findings
        if: steps.audit.outputs.total_issues > 0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Parse SwiftLint for critical/high severity
          HIGH_ISSUES=$(jq '[.[] | select(.severity == "error" or .severity == "warning")] | length' swiftlint-report.json 2>/dev/null || echo "0")

          if [ "$HIGH_ISSUES" -gt 0 ]; then
            # Check if audit issue already exists
            EXISTING=$(gh issue list --label "audit" --state open --json number --jq 'length')

            if [ "$EXISTING" -eq 0 ]; then
              gh issue create \
                --title "Audit: $HIGH_ISSUES issues found ($(date +%Y-%m-%d))" \
                --body "## Weekly Audit Results

**Score:** ${{ steps.audit.outputs.score }}/10
**Total Issues:** ${{ steps.audit.outputs.total_issues }}

### Breakdown
- SwiftLint: $(jq 'length' swiftlint-report.json 2>/dev/null || echo '0')
- Build Warnings: $(wc -l < build-warnings.txt | tr -d ' ')

### Next Steps
Run \`/audit --fix\` to address these issues.

---
*Generated by scheduled audit workflow*" \
                --label "audit,automated"
            fi
          fi

      - name: Commit Report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .claude/

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: scheduled audit report $(date +%Y-%m-%d)

Score: ${{ steps.audit.outputs.score }}/10
Issues: ${{ steps.audit.outputs.total_issues }}

Co-Authored-By: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

            git push
          fi

      - name: Summary
        run: |
          echo "## Audit Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Score:** ${{ steps.audit.outputs.score }}/10" >> $GITHUB_STEP_SUMMARY
          echo "**Total Issues:** ${{ steps.audit.outputs.total_issues }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Report saved to: ${{ steps.audit.outputs.report_file }}" >> $GITHUB_STEP_SUMMARY
